name: Pytest CI

on:
  pull_request:
  push:
    branches:
    - master
    - pytest

jobs:
  pytest:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - python: "3.7"
            node: 20
            os: ubuntu-22.04
          - python: "3.11"
            node: 20
            os: macos-15
          - python: "3.13"
            node: 22
            os: ubuntu-24.04
          - python: "3.14"
            node: 24
            os: windows-2025
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node }}
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python }}
    - name: Install project dependencies
      run: |
        npm install -g less
        pip install -r requirements-dev.txt
        git clone https://github.com/thunderbird/thunderbird-notes.git libs/thunderbird_notes
        git clone -b production https://github.com/mozilla-releng/product-details.git libs/product-details
    - name: Run pytest
      run: |
        python -m pytest tests
